first_job:
  stage: build
  script:
    - cd first/hello
    - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o main main.go
    - cd ../../infra
    - terraform init
    - terraform apply -auto-approve
