// Code generated by ogen, DO NOT EDIT.
package dip

type GetAktivitaetListRes interface {
	getAktivitaetListRes()
}

type GetAktivitaetRes interface {
	getAktivitaetRes()
}

type GetDrucksacheListRes interface {
	getDrucksacheListRes()
}

type GetDrucksacheRes interface {
	getDrucksacheRes()
}

type GetDrucksacheTextListRes interface {
	getDrucksacheTextListRes()
}

type GetDrucksacheTextRes interface {
	getDrucksacheTextRes()
}

type GetPersonListRes interface {
	getPersonListRes()
}

type GetPersonRes interface {
	getPersonRes()
}

type GetPlenarprotokollListRes interface {
	getPlenarprotokollListRes()
}

type GetPlenarprotokollRes interface {
	getPlenarprotokollRes()
}

type GetPlenarprotokollTextListRes interface {
	getPlenarprotokollTextListRes()
}

type GetPlenarprotokollTextRes interface {
	getPlenarprotokollTextRes()
}

type GetVorgangListRes interface {
	getVorgangListRes()
}

type GetVorgangRes interface {
	getVorgangRes()
}

type GetVorgangspositionListRes interface {
	getVorgangspositionListRes()
}

type GetVorgangspositionRes interface {
	getVorgangspositionRes()
}
