// Code generated by ogen, DO NOT EDIT.

package dip

// GetAktivitaetParams is parameters of getAktivitaet operation.
type GetAktivitaetParams struct {
	ID int
	// Steuert das Datenformat der Antwort, möglich sind JSON (voreingestellt) oder XML.
	Format OptGetAktivitaetFormat
}

// GetAktivitaetListParams is parameters of getAktivitaetList operation.
type GetAktivitaetListParams struct {
	// Frühestes Aktualisierungsdatum der Entität
	// Selektiert Entitäten in einem Datumsbereich basierend auf dem letzten Aktualisierungsdatum.
	FAktualisiertStart OptDateTime
	// Spätestes Aktualisierungsdatum der Entität
	// Selektiert Entitäten in einem Datumsbereich basierend auf dem letzten Aktualisierungsdatum.
	FAktualisiertEnd OptDateTime
	// Frühestes Datum der Entität
	// Selektiert Entitäten in einem Datumsbereich basierend auf dem Dokumentdatum. Für Vorgänge und
	// Personen wird der Datumsbereich aller zugehörigen Dokumente herangezogen.
	FDatumStart OptDatum
	// Spätestes Datum der Entität
	// Selektiert Entitäten in einem Datumsbereich basierend auf dem Dokumentdatum. Für Vorgänge und
	// Personen wird der Datumsbereich aller zugehörigen Dokumente herangezogen.
	FDatumEnd OptDatum
	// Deskriptor
	// Selektiert alle Entitäten, die mit dem angegebenen Deskriptor verknüpft sind.
	// Kann wiederholt werden, um die Schnittmenge mehrerer Deskriptoren zu selektieren. Hinterlegt ist
	// eine UND-Suche.
	// Eine ODER-Suche über mehrere Deskriptoren ist mit einer einzigen Abfrage nicht möglich. Die
	// Deskriptoren müssen dazu einzeln abgefragt werden.
	FDeskriptor []string
	// Drucksache oder Plenarprotokoll
	// Selektiert alle Entitäten, die mit der angegebenen Dokumentart verknüpft sind.
	FDokumentart OptGetAktivitaetListFDokumentart
	// Dokumentnummer einer Drucksache oder eines Plenarprotokolls
	// Selektiert alle Entitäten, die mit der angegebenen Dokumentnummer verknüpft sind.
	// Kann wiederholt werden, um mehrere Dokumentnummern zu selektieren. Hinterlegt ist eine ODER-Suche.
	FDokumentnummer []string
	// ID einer verknüpften Drucksache
	// Selektiert alle Entitäten, die mit der angegebenen Drucksache verknüpft sind.
	FDrucksache OptInt
	// Typ der Drucksache
	// Selektiert alle Entitäten, die mit dem angegebenen Drucksachetyp verknüpft sind.
	FDrucksachetyp OptString
	// Fragenummer/Listenziffer
	// Selektiert alle Entitäten, die mit der angegebenen Fragenummer in einer Drucksache verknüpft
	// sind.
	// Kann wiederholt werden, um mehrere Fragenummern zu selektieren. Hinterlegt ist eine ODER-Suche.
	FFrageNummer []string
	// ID der Entität
	// Kann wiederholt werden, um mehrere Entitäten zu selektieren.
	FID []int
	// ID eines verknüpften Plenarprotokolls
	// Selektiert alle Entitäten, die mit dem angegebenen Plenarprotokoll verknüpft sind.
	FPlenarprotokoll OptInt
	// Sachgebiet
	// Selektiert alle Entitäten, die mit dem angegebenen Sachgebiet verknüpft sind.
	// Kann wiederholt werden, um die Schnittmenge mehrerer Sachgebiete zu selektieren. Hinterlegt ist
	// eine UND-Suche.
	// Eine ODER-Suche über mehrere Sachgebiete ist mit einer einzigen Abfrage nicht möglich. Die
	// Sachgebiete müssen dazu einzeln abgefragt werden.
	FSachgebiet []string
	// Urheber
	// Selektiert alle Entitäten, die mit dem angegebenen Urheber in einer Drucksache verknüpft sind.
	// Kann wiederholt werden, um die Schnittmenge mehrerer Urheber zu selektieren. Hinterlegt ist eine
	// UND-Suche.
	// Eine ODER-Suche über mehrere Urheber ist mit einer einzigen Abfrage nicht möglich. Die Urheber
	// müssen dazu einzeln abgefragt werden.
	FUrheber []string
	// Vorgangstyp
	// Selektiert alle Entitäten, die dem angegebenen Vorgangstyp zugeordnet sind.
	// Kann wiederholt werden, um mehrere Vorgangstypen zu selektieren. Hinterlegt ist eine ODER-Suche.
	FVorgangstyp []string
	// Vorgangstyp-Notation
	// Selektiert alle Entitäten, die der angegebenen Vorgangstyp-Notation zugeordnet sind.
	// Kann wiederholt werden, um mehrere Vorgangstypen zu selektieren. Hinterlegt ist eine ODER-Suche.
	FVorgangstypNotation []int
	// Nummer der Wahlperiode
	// Selektiert alle Entitäten, die der angegebenen Wahlperiode zugeordnet sind.
	// Kann wiederholt werden, um mehrere Wahlperioden zu selektieren. Hinterlegt ist eine ODER-Suche.
	FWahlperiode []int
	// Zuordnung der Entität zum Bundestag, Bundesrat, Bundesversammlung oder Europakammer.
	FZuordnung OptZuordnung
	// Position des Cursors zur Anfrage weiterer Entitäten
	// Übersteigt die Anzahl der gefundenen Entitäten das jeweilige Limit, muss eine Folgeanfrage
	// gestellt werden, um weitere Entitäten zu laden.
	// Eine Folgeanfrage wird gebildet, indem alle Parameter der ursprünglichen Anfrage wiederholt
	// werden und zusätzlich der cursor Parameter der letzten Antwort eingesetzt wird.
	// Es können solange Folgeanfragen gestellt werden, bis sich der cursor nicht mehr ändert. Dies
	// signalisiert, dass alle Entitäten geladen wurden.
	Cursor OptString
	// Steuert das Datenformat der Antwort, möglich sind JSON (voreingestellt) oder XML.
	Format OptGetAktivitaetListFormat
}

// GetDrucksacheParams is parameters of getDrucksache operation.
type GetDrucksacheParams struct {
	ID int
	// Steuert das Datenformat der Antwort, möglich sind JSON (voreingestellt) oder XML.
	Format OptGetDrucksacheFormat
}

// GetDrucksacheListParams is parameters of getDrucksacheList operation.
type GetDrucksacheListParams struct {
	// Frühestes Aktualisierungsdatum der Entität
	// Selektiert Entitäten in einem Datumsbereich basierend auf dem letzten Aktualisierungsdatum.
	FAktualisiertStart OptDateTime
	// Spätestes Aktualisierungsdatum der Entität
	// Selektiert Entitäten in einem Datumsbereich basierend auf dem letzten Aktualisierungsdatum.
	FAktualisiertEnd OptDateTime
	// Frühestes Datum der Entität
	// Selektiert Entitäten in einem Datumsbereich basierend auf dem Dokumentdatum. Für Vorgänge und
	// Personen wird der Datumsbereich aller zugehörigen Dokumente herangezogen.
	FDatumStart OptDatum
	// Spätestes Datum der Entität
	// Selektiert Entitäten in einem Datumsbereich basierend auf dem Dokumentdatum. Für Vorgänge und
	// Personen wird der Datumsbereich aller zugehörigen Dokumente herangezogen.
	FDatumEnd OptDatum
	// Dokumentnummer einer Drucksache oder eines Plenarprotokolls
	// Selektiert alle Entitäten, die mit der angegebenen Dokumentnummer verknüpft sind.
	// Kann wiederholt werden, um mehrere Dokumentnummern zu selektieren. Hinterlegt ist eine ODER-Suche.
	FDokumentnummer []string
	// Typ der Drucksache
	// Selektiert alle Entitäten, die mit dem angegebenen Drucksachetyp verknüpft sind.
	FDrucksachetyp OptString
	// ID der Entität
	// Kann wiederholt werden, um mehrere Entitäten zu selektieren.
	FID []int
	// Ressort (federführend)
	// Selektiert alle Entitäten, die mit dem angegebenen federführenden Ressort in einer Drucksache
	// verknüpft sind.
	// Kann wiederholt werden, um die Schnittmenge mehrerer Ressorts zu selektieren. Hinterlegt ist eine
	// UND-Suche.
	// Eine ODER-Suche über mehrere federführende Ressorts ist mit einer einzigen Abfrage nicht
	// möglich. Die federführenden Ressorts müssen dazu einzeln abgefragt werden.
	FRessortFdf []string
	// Titel
	// Selektiert alle Entitäten, die den angegebenen Suchbegriff im Titel enthalten.
	// Kann wiederholt werden, um mehrere Titel zu selektieren. Hinterlegt ist eine ODER-Suche.
	// Eine Einzelwortsuche ist möglich. Mehrere Suchbegriffe hintereinander werden als Phrase gesucht.
	FTitel []string
	// Urheber
	// Selektiert alle Entitäten, die mit dem angegebenen Urheber in einer Drucksache verknüpft sind.
	// Kann wiederholt werden, um die Schnittmenge mehrerer Urheber zu selektieren. Hinterlegt ist eine
	// UND-Suche.
	// Eine ODER-Suche über mehrere Urheber ist mit einer einzigen Abfrage nicht möglich. Die Urheber
	// müssen dazu einzeln abgefragt werden.
	FUrheber []string
	// Vorgangstyp
	// Selektiert alle Entitäten, die dem angegebenen Vorgangstyp zugeordnet sind.
	// Kann wiederholt werden, um mehrere Vorgangstypen zu selektieren. Hinterlegt ist eine ODER-Suche.
	FVorgangstyp []string
	// Vorgangstyp-Notation
	// Selektiert alle Entitäten, die der angegebenen Vorgangstyp-Notation zugeordnet sind.
	// Kann wiederholt werden, um mehrere Vorgangstypen zu selektieren. Hinterlegt ist eine ODER-Suche.
	FVorgangstypNotation []int
	// Nummer der Wahlperiode
	// Selektiert alle Entitäten, die der angegebenen Wahlperiode zugeordnet sind.
	// Kann wiederholt werden, um mehrere Wahlperioden zu selektieren. Hinterlegt ist eine ODER-Suche.
	FWahlperiode []int
	// Zuordnung der Entität zum Bundestag, Bundesrat, Bundesversammlung oder Europakammer.
	FZuordnung OptZuordnung
	// Position des Cursors zur Anfrage weiterer Entitäten
	// Übersteigt die Anzahl der gefundenen Entitäten das jeweilige Limit, muss eine Folgeanfrage
	// gestellt werden, um weitere Entitäten zu laden.
	// Eine Folgeanfrage wird gebildet, indem alle Parameter der ursprünglichen Anfrage wiederholt
	// werden und zusätzlich der cursor Parameter der letzten Antwort eingesetzt wird.
	// Es können solange Folgeanfragen gestellt werden, bis sich der cursor nicht mehr ändert. Dies
	// signalisiert, dass alle Entitäten geladen wurden.
	Cursor OptString
	// Steuert das Datenformat der Antwort, möglich sind JSON (voreingestellt) oder XML.
	Format OptGetDrucksacheListFormat
}

// GetDrucksacheTextParams is parameters of getDrucksacheText operation.
type GetDrucksacheTextParams struct {
	ID int
	// Steuert das Datenformat der Antwort, möglich sind JSON (voreingestellt) oder XML.
	Format OptGetDrucksacheTextFormat
}

// GetDrucksacheTextListParams is parameters of getDrucksacheTextList operation.
type GetDrucksacheTextListParams struct {
	// Frühestes Aktualisierungsdatum der Entität
	// Selektiert Entitäten in einem Datumsbereich basierend auf dem letzten Aktualisierungsdatum.
	FAktualisiertStart OptDateTime
	// Spätestes Aktualisierungsdatum der Entität
	// Selektiert Entitäten in einem Datumsbereich basierend auf dem letzten Aktualisierungsdatum.
	FAktualisiertEnd OptDateTime
	// Frühestes Datum der Entität
	// Selektiert Entitäten in einem Datumsbereich basierend auf dem Dokumentdatum. Für Vorgänge und
	// Personen wird der Datumsbereich aller zugehörigen Dokumente herangezogen.
	FDatumStart OptDatum
	// Spätestes Datum der Entität
	// Selektiert Entitäten in einem Datumsbereich basierend auf dem Dokumentdatum. Für Vorgänge und
	// Personen wird der Datumsbereich aller zugehörigen Dokumente herangezogen.
	FDatumEnd OptDatum
	// Dokumentnummer einer Drucksache oder eines Plenarprotokolls
	// Selektiert alle Entitäten, die mit der angegebenen Dokumentnummer verknüpft sind.
	// Kann wiederholt werden, um mehrere Dokumentnummern zu selektieren. Hinterlegt ist eine ODER-Suche.
	FDokumentnummer []string
	// Typ der Drucksache
	// Selektiert alle Entitäten, die mit dem angegebenen Drucksachetyp verknüpft sind.
	FDrucksachetyp OptString
	// ID der Entität
	// Kann wiederholt werden, um mehrere Entitäten zu selektieren.
	FID []int
	// Ressort (federführend)
	// Selektiert alle Entitäten, die mit dem angegebenen federführenden Ressort in einer Drucksache
	// verknüpft sind.
	// Kann wiederholt werden, um die Schnittmenge mehrerer Ressorts zu selektieren. Hinterlegt ist eine
	// UND-Suche.
	// Eine ODER-Suche über mehrere federführende Ressorts ist mit einer einzigen Abfrage nicht
	// möglich. Die federführenden Ressorts müssen dazu einzeln abgefragt werden.
	FRessortFdf []string
	// Titel
	// Selektiert alle Entitäten, die den angegebenen Suchbegriff im Titel enthalten.
	// Kann wiederholt werden, um mehrere Titel zu selektieren. Hinterlegt ist eine ODER-Suche.
	// Eine Einzelwortsuche ist möglich. Mehrere Suchbegriffe hintereinander werden als Phrase gesucht.
	FTitel []string
	// Urheber
	// Selektiert alle Entitäten, die mit dem angegebenen Urheber in einer Drucksache verknüpft sind.
	// Kann wiederholt werden, um die Schnittmenge mehrerer Urheber zu selektieren. Hinterlegt ist eine
	// UND-Suche.
	// Eine ODER-Suche über mehrere Urheber ist mit einer einzigen Abfrage nicht möglich. Die Urheber
	// müssen dazu einzeln abgefragt werden.
	FUrheber []string
	// Vorgangstyp
	// Selektiert alle Entitäten, die dem angegebenen Vorgangstyp zugeordnet sind.
	// Kann wiederholt werden, um mehrere Vorgangstypen zu selektieren. Hinterlegt ist eine ODER-Suche.
	FVorgangstyp []string
	// Vorgangstyp-Notation
	// Selektiert alle Entitäten, die der angegebenen Vorgangstyp-Notation zugeordnet sind.
	// Kann wiederholt werden, um mehrere Vorgangstypen zu selektieren. Hinterlegt ist eine ODER-Suche.
	FVorgangstypNotation []int
	// Nummer der Wahlperiode
	// Selektiert alle Entitäten, die der angegebenen Wahlperiode zugeordnet sind.
	// Kann wiederholt werden, um mehrere Wahlperioden zu selektieren. Hinterlegt ist eine ODER-Suche.
	FWahlperiode []int
	// Zuordnung der Entität zum Bundestag, Bundesrat, Bundesversammlung oder Europakammer.
	FZuordnung OptZuordnung
	// Position des Cursors zur Anfrage weiterer Entitäten
	// Übersteigt die Anzahl der gefundenen Entitäten das jeweilige Limit, muss eine Folgeanfrage
	// gestellt werden, um weitere Entitäten zu laden.
	// Eine Folgeanfrage wird gebildet, indem alle Parameter der ursprünglichen Anfrage wiederholt
	// werden und zusätzlich der cursor Parameter der letzten Antwort eingesetzt wird.
	// Es können solange Folgeanfragen gestellt werden, bis sich der cursor nicht mehr ändert. Dies
	// signalisiert, dass alle Entitäten geladen wurden.
	Cursor OptString
	// Steuert das Datenformat der Antwort, möglich sind JSON (voreingestellt) oder XML.
	Format OptGetDrucksacheTextListFormat
}

// GetPersonParams is parameters of getPerson operation.
type GetPersonParams struct {
	ID int
	// Steuert das Datenformat der Antwort, möglich sind JSON (voreingestellt) oder XML.
	Format OptGetPersonFormat
}

// GetPersonListParams is parameters of getPersonList operation.
type GetPersonListParams struct {
	// Frühestes Aktualisierungsdatum der Entität
	// Selektiert Entitäten in einem Datumsbereich basierend auf dem letzten Aktualisierungsdatum.
	FAktualisiertStart OptDateTime
	// Spätestes Aktualisierungsdatum der Entität
	// Selektiert Entitäten in einem Datumsbereich basierend auf dem letzten Aktualisierungsdatum.
	FAktualisiertEnd OptDateTime
	// Frühestes Datum der Entität
	// Selektiert Entitäten in einem Datumsbereich basierend auf dem Dokumentdatum. Für Vorgänge und
	// Personen wird der Datumsbereich aller zugehörigen Dokumente herangezogen.
	FDatumStart OptDatum
	// Spätestes Datum der Entität
	// Selektiert Entitäten in einem Datumsbereich basierend auf dem Dokumentdatum. Für Vorgänge und
	// Personen wird der Datumsbereich aller zugehörigen Dokumente herangezogen.
	FDatumEnd OptDatum
	// ID der Entität
	// Kann wiederholt werden, um mehrere Entitäten zu selektieren.
	FID []int
	// Nummer der Wahlperiode
	// Selektiert alle Entitäten, die der angegebenen Wahlperiode zugeordnet sind.
	// Kann wiederholt werden, um mehrere Wahlperioden zu selektieren. Hinterlegt ist eine ODER-Suche.
	FWahlperiode []int
	// Position des Cursors zur Anfrage weiterer Entitäten
	// Übersteigt die Anzahl der gefundenen Entitäten das jeweilige Limit, muss eine Folgeanfrage
	// gestellt werden, um weitere Entitäten zu laden.
	// Eine Folgeanfrage wird gebildet, indem alle Parameter der ursprünglichen Anfrage wiederholt
	// werden und zusätzlich der cursor Parameter der letzten Antwort eingesetzt wird.
	// Es können solange Folgeanfragen gestellt werden, bis sich der cursor nicht mehr ändert. Dies
	// signalisiert, dass alle Entitäten geladen wurden.
	Cursor OptString
	// Steuert das Datenformat der Antwort, möglich sind JSON (voreingestellt) oder XML.
	Format OptGetPersonListFormat
}

// GetPlenarprotokollParams is parameters of getPlenarprotokoll operation.
type GetPlenarprotokollParams struct {
	ID int
	// Steuert das Datenformat der Antwort, möglich sind JSON (voreingestellt) oder XML.
	Format OptGetPlenarprotokollFormat
}

// GetPlenarprotokollListParams is parameters of getPlenarprotokollList operation.
type GetPlenarprotokollListParams struct {
	// Frühestes Aktualisierungsdatum der Entität
	// Selektiert Entitäten in einem Datumsbereich basierend auf dem letzten Aktualisierungsdatum.
	FAktualisiertStart OptDateTime
	// Spätestes Aktualisierungsdatum der Entität
	// Selektiert Entitäten in einem Datumsbereich basierend auf dem letzten Aktualisierungsdatum.
	FAktualisiertEnd OptDateTime
	// Frühestes Datum der Entität
	// Selektiert Entitäten in einem Datumsbereich basierend auf dem Dokumentdatum. Für Vorgänge und
	// Personen wird der Datumsbereich aller zugehörigen Dokumente herangezogen.
	FDatumStart OptDatum
	// Spätestes Datum der Entität
	// Selektiert Entitäten in einem Datumsbereich basierend auf dem Dokumentdatum. Für Vorgänge und
	// Personen wird der Datumsbereich aller zugehörigen Dokumente herangezogen.
	FDatumEnd OptDatum
	// Dokumentnummer einer Drucksache oder eines Plenarprotokolls
	// Selektiert alle Entitäten, die mit der angegebenen Dokumentnummer verknüpft sind.
	// Kann wiederholt werden, um mehrere Dokumentnummern zu selektieren. Hinterlegt ist eine ODER-Suche.
	FDokumentnummer []string
	// ID der Entität
	// Kann wiederholt werden, um mehrere Entitäten zu selektieren.
	FID []int
	// Vorgangstyp
	// Selektiert alle Entitäten, die dem angegebenen Vorgangstyp zugeordnet sind.
	// Kann wiederholt werden, um mehrere Vorgangstypen zu selektieren. Hinterlegt ist eine ODER-Suche.
	FVorgangstyp []string
	// Vorgangstyp-Notation
	// Selektiert alle Entitäten, die der angegebenen Vorgangstyp-Notation zugeordnet sind.
	// Kann wiederholt werden, um mehrere Vorgangstypen zu selektieren. Hinterlegt ist eine ODER-Suche.
	FVorgangstypNotation []int
	// Nummer der Wahlperiode
	// Selektiert alle Entitäten, die der angegebenen Wahlperiode zugeordnet sind.
	// Kann wiederholt werden, um mehrere Wahlperioden zu selektieren. Hinterlegt ist eine ODER-Suche.
	FWahlperiode []int
	// Zuordnung der Entität zum Bundestag, Bundesrat, Bundesversammlung oder Europakammer.
	FZuordnung OptZuordnung
	// Position des Cursors zur Anfrage weiterer Entitäten
	// Übersteigt die Anzahl der gefundenen Entitäten das jeweilige Limit, muss eine Folgeanfrage
	// gestellt werden, um weitere Entitäten zu laden.
	// Eine Folgeanfrage wird gebildet, indem alle Parameter der ursprünglichen Anfrage wiederholt
	// werden und zusätzlich der cursor Parameter der letzten Antwort eingesetzt wird.
	// Es können solange Folgeanfragen gestellt werden, bis sich der cursor nicht mehr ändert. Dies
	// signalisiert, dass alle Entitäten geladen wurden.
	Cursor OptString
	// Steuert das Datenformat der Antwort, möglich sind JSON (voreingestellt) oder XML.
	Format OptGetPlenarprotokollListFormat
}

// GetPlenarprotokollTextParams is parameters of getPlenarprotokollText operation.
type GetPlenarprotokollTextParams struct {
	ID int
	// Steuert das Datenformat der Antwort, möglich sind JSON (voreingestellt) oder XML.
	Format OptGetPlenarprotokollTextFormat
}

// GetPlenarprotokollTextListParams is parameters of getPlenarprotokollTextList operation.
type GetPlenarprotokollTextListParams struct {
	// Frühestes Aktualisierungsdatum der Entität
	// Selektiert Entitäten in einem Datumsbereich basierend auf dem letzten Aktualisierungsdatum.
	FAktualisiertStart OptDateTime
	// Spätestes Aktualisierungsdatum der Entität
	// Selektiert Entitäten in einem Datumsbereich basierend auf dem letzten Aktualisierungsdatum.
	FAktualisiertEnd OptDateTime
	// Frühestes Datum der Entität
	// Selektiert Entitäten in einem Datumsbereich basierend auf dem Dokumentdatum. Für Vorgänge und
	// Personen wird der Datumsbereich aller zugehörigen Dokumente herangezogen.
	FDatumStart OptDatum
	// Spätestes Datum der Entität
	// Selektiert Entitäten in einem Datumsbereich basierend auf dem Dokumentdatum. Für Vorgänge und
	// Personen wird der Datumsbereich aller zugehörigen Dokumente herangezogen.
	FDatumEnd OptDatum
	// Dokumentnummer einer Drucksache oder eines Plenarprotokolls
	// Selektiert alle Entitäten, die mit der angegebenen Dokumentnummer verknüpft sind.
	// Kann wiederholt werden, um mehrere Dokumentnummern zu selektieren. Hinterlegt ist eine ODER-Suche.
	FDokumentnummer []string
	// ID der Entität
	// Kann wiederholt werden, um mehrere Entitäten zu selektieren.
	FID []int
	// Vorgangstyp
	// Selektiert alle Entitäten, die dem angegebenen Vorgangstyp zugeordnet sind.
	// Kann wiederholt werden, um mehrere Vorgangstypen zu selektieren. Hinterlegt ist eine ODER-Suche.
	FVorgangstyp []string
	// Vorgangstyp-Notation
	// Selektiert alle Entitäten, die der angegebenen Vorgangstyp-Notation zugeordnet sind.
	// Kann wiederholt werden, um mehrere Vorgangstypen zu selektieren. Hinterlegt ist eine ODER-Suche.
	FVorgangstypNotation []int
	// Nummer der Wahlperiode
	// Selektiert alle Entitäten, die der angegebenen Wahlperiode zugeordnet sind.
	// Kann wiederholt werden, um mehrere Wahlperioden zu selektieren. Hinterlegt ist eine ODER-Suche.
	FWahlperiode []int
	// Zuordnung der Entität zum Bundestag, Bundesrat, Bundesversammlung oder Europakammer.
	FZuordnung OptZuordnung
	// Position des Cursors zur Anfrage weiterer Entitäten
	// Übersteigt die Anzahl der gefundenen Entitäten das jeweilige Limit, muss eine Folgeanfrage
	// gestellt werden, um weitere Entitäten zu laden.
	// Eine Folgeanfrage wird gebildet, indem alle Parameter der ursprünglichen Anfrage wiederholt
	// werden und zusätzlich der cursor Parameter der letzten Antwort eingesetzt wird.
	// Es können solange Folgeanfragen gestellt werden, bis sich der cursor nicht mehr ändert. Dies
	// signalisiert, dass alle Entitäten geladen wurden.
	Cursor OptString
	// Steuert das Datenformat der Antwort, möglich sind JSON (voreingestellt) oder XML.
	Format OptGetPlenarprotokollTextListFormat
}

// GetVorgangParams is parameters of getVorgang operation.
type GetVorgangParams struct {
	ID int
	// Steuert das Datenformat der Antwort, möglich sind JSON (voreingestellt) oder XML.
	Format OptGetVorgangFormat
}

// GetVorgangListParams is parameters of getVorgangList operation.
type GetVorgangListParams struct {
	// Frühestes Aktualisierungsdatum der Entität
	// Selektiert Entitäten in einem Datumsbereich basierend auf dem letzten Aktualisierungsdatum.
	FAktualisiertStart OptDateTime
	// Spätestes Aktualisierungsdatum der Entität
	// Selektiert Entitäten in einem Datumsbereich basierend auf dem letzten Aktualisierungsdatum.
	FAktualisiertEnd OptDateTime
	// Beratungsstand
	// Selektiert alle Entitäten, die dem angegebenen Beratungsstand zugeordnet sind.
	// Kann wiederholt werden, um mehrere Beratungsstände zu selektieren. Hinterlegt ist eine ODER-Suche.
	FBeratungsstand []string
	// Frühestes Datum der Entität
	// Selektiert Entitäten in einem Datumsbereich basierend auf dem Dokumentdatum. Für Vorgänge und
	// Personen wird der Datumsbereich aller zugehörigen Dokumente herangezogen.
	FDatumStart OptDatum
	// Spätestes Datum der Entität
	// Selektiert Entitäten in einem Datumsbereich basierend auf dem Dokumentdatum. Für Vorgänge und
	// Personen wird der Datumsbereich aller zugehörigen Dokumente herangezogen.
	FDatumEnd OptDatum
	// Deskriptor
	// Selektiert alle Entitäten, die mit dem angegebenen Deskriptor verknüpft sind.
	// Kann wiederholt werden, um die Schnittmenge mehrerer Deskriptoren zu selektieren. Hinterlegt ist
	// eine UND-Suche.
	// Eine ODER-Suche über mehrere Deskriptoren ist mit einer einzigen Abfrage nicht möglich. Die
	// Deskriptoren müssen dazu einzeln abgefragt werden.
	FDeskriptor []string
	// Drucksache oder Plenarprotokoll
	// Selektiert alle Entitäten, die mit der angegebenen Dokumentart verknüpft sind.
	FDokumentart OptGetVorgangListFDokumentart
	// Dokumentnummer einer Drucksache oder eines Plenarprotokolls
	// Selektiert alle Entitäten, die mit der angegebenen Dokumentnummer verknüpft sind.
	// Kann wiederholt werden, um mehrere Dokumentnummern zu selektieren. Hinterlegt ist eine ODER-Suche.
	FDokumentnummer []string
	// ID einer verknüpften Drucksache
	// Selektiert alle Entitäten, die mit der angegebenen Drucksache verknüpft sind.
	FDrucksache OptInt
	// Typ der Drucksache
	// Selektiert alle Entitäten, die mit dem angegebenen Drucksachetyp verknüpft sind.
	FDrucksachetyp OptString
	// Fragenummer/Listenziffer
	// Selektiert alle Entitäten, die mit der angegebenen Fragenummer in einer Drucksache verknüpft
	// sind.
	// Kann wiederholt werden, um mehrere Fragenummern zu selektieren. Hinterlegt ist eine ODER-Suche.
	FFrageNummer []string
	// GESTA-Ordnungsnummer
	// Selektiert alle Entitäten, die der angegebenen GESTA-Ordnungsnummer zugeordnet sind.
	// Kann wiederholt werden, um mehrere Ordnungsnummern zu selektieren. Hinterlegt ist eine ODER-Suche.
	FGesta []string
	// ID der Entität
	// Kann wiederholt werden, um mehrere Entitäten zu selektieren.
	FID []int
	// Initiative
	// Selektiert alle Entitäten, die mit dem angegebenen Urheber im Basisdokument verknüpft sind.
	// Kann wiederholt werden, um die Schnittmenge mehrerer Initianten zu selektieren. Hinterlegt ist
	// eine UND-Suche.
	// Eine ODER-Suche über mehrere Initianten ist mit einer einzigen Abfrage nicht möglich. Die
	// Initianten müssen dazu einzeln abgefragt werden.
	FInitiative []string
	// ID eines verknüpften Plenarprotokolls
	// Selektiert alle Entitäten, die mit dem angegebenen Plenarprotokoll verknüpft sind.
	FPlenarprotokoll OptInt
	// Ressort (federführend)
	// Selektiert alle Entitäten, die mit dem angegebenen federführenden Ressort in einer Drucksache
	// verknüpft sind.
	// Kann wiederholt werden, um die Schnittmenge mehrerer Ressorts zu selektieren. Hinterlegt ist eine
	// UND-Suche.
	// Eine ODER-Suche über mehrere federführende Ressorts ist mit einer einzigen Abfrage nicht
	// möglich. Die federführenden Ressorts müssen dazu einzeln abgefragt werden.
	FRessortFdf []string
	// Sachgebiet
	// Selektiert alle Entitäten, die mit dem angegebenen Sachgebiet verknüpft sind.
	// Kann wiederholt werden, um die Schnittmenge mehrerer Sachgebiete zu selektieren. Hinterlegt ist
	// eine UND-Suche.
	// Eine ODER-Suche über mehrere Sachgebiete ist mit einer einzigen Abfrage nicht möglich. Die
	// Sachgebiete müssen dazu einzeln abgefragt werden.
	FSachgebiet []string
	// Titel
	// Selektiert alle Entitäten, die den angegebenen Suchbegriff im Titel enthalten.
	// Kann wiederholt werden, um mehrere Titel zu selektieren. Hinterlegt ist eine ODER-Suche.
	// Eine Einzelwortsuche ist möglich. Mehrere Suchbegriffe hintereinander werden als Phrase gesucht.
	FTitel []string
	// Urheber
	// Selektiert alle Entitäten, die mit dem angegebenen Urheber in einer Drucksache verknüpft sind.
	// Kann wiederholt werden, um die Schnittmenge mehrerer Urheber zu selektieren. Hinterlegt ist eine
	// UND-Suche.
	// Eine ODER-Suche über mehrere Urheber ist mit einer einzigen Abfrage nicht möglich. Die Urheber
	// müssen dazu einzeln abgefragt werden.
	FUrheber []string
	// Fundstelle der Verkündung
	// Selektiert alle Entitäten, welche den angegebenen Suchbegriff in der Fundstelle der Verkündung
	// enthalten.
	// Kann wiederholt werden, um mehrere Fundstellen zu selektieren. Hinterlegt ist eine ODER-Suche.
	// Eine Einzelwortsuche (z.B. nach dem Verkündungsblatt) ist möglich.
	FVerkuendungFundstelle []string
	// Vorgangstyp
	// Selektiert alle Entitäten, die dem angegebenen Vorgangstyp zugeordnet sind.
	// Kann wiederholt werden, um mehrere Vorgangstypen zu selektieren. Hinterlegt ist eine ODER-Suche.
	FVorgangstyp []string
	// Vorgangstyp-Notation
	// Selektiert alle Entitäten, die der angegebenen Vorgangstyp-Notation zugeordnet sind.
	// Kann wiederholt werden, um mehrere Vorgangstypen zu selektieren. Hinterlegt ist eine ODER-Suche.
	FVorgangstypNotation []int
	// Nummer der Wahlperiode
	// Selektiert alle Entitäten, die der angegebenen Wahlperiode zugeordnet sind.
	// Kann wiederholt werden, um mehrere Wahlperioden zu selektieren. Hinterlegt ist eine ODER-Suche.
	FWahlperiode []int
	// Position des Cursors zur Anfrage weiterer Entitäten
	// Übersteigt die Anzahl der gefundenen Entitäten das jeweilige Limit, muss eine Folgeanfrage
	// gestellt werden, um weitere Entitäten zu laden.
	// Eine Folgeanfrage wird gebildet, indem alle Parameter der ursprünglichen Anfrage wiederholt
	// werden und zusätzlich der cursor Parameter der letzten Antwort eingesetzt wird.
	// Es können solange Folgeanfragen gestellt werden, bis sich der cursor nicht mehr ändert. Dies
	// signalisiert, dass alle Entitäten geladen wurden.
	Cursor OptString
	// Steuert das Datenformat der Antwort, möglich sind JSON (voreingestellt) oder XML.
	Format OptGetVorgangListFormat
}

// GetVorgangspositionParams is parameters of getVorgangsposition operation.
type GetVorgangspositionParams struct {
	ID int
	// Steuert das Datenformat der Antwort, möglich sind JSON (voreingestellt) oder XML.
	Format OptGetVorgangspositionFormat
}

// GetVorgangspositionListParams is parameters of getVorgangspositionList operation.
type GetVorgangspositionListParams struct {
	// ID einer verknüpften Aktivität
	// Selektiert alle Entitäten, die mit der angegebenen Aktivität verknüpft sind.
	FAktivitaet OptInt
	// Frühestes Aktualisierungsdatum der Entität
	// Selektiert Entitäten in einem Datumsbereich basierend auf dem letzten Aktualisierungsdatum.
	FAktualisiertStart OptDateTime
	// Spätestes Aktualisierungsdatum der Entität
	// Selektiert Entitäten in einem Datumsbereich basierend auf dem letzten Aktualisierungsdatum.
	FAktualisiertEnd OptDateTime
	// Frühestes Datum der Entität
	// Selektiert Entitäten in einem Datumsbereich basierend auf dem Dokumentdatum. Für Vorgänge und
	// Personen wird der Datumsbereich aller zugehörigen Dokumente herangezogen.
	FDatumStart OptDatum
	// Spätestes Datum der Entität
	// Selektiert Entitäten in einem Datumsbereich basierend auf dem Dokumentdatum. Für Vorgänge und
	// Personen wird der Datumsbereich aller zugehörigen Dokumente herangezogen.
	FDatumEnd OptDatum
	// Drucksache oder Plenarprotokoll
	// Selektiert alle Entitäten, die mit der angegebenen Dokumentart verknüpft sind.
	FDokumentart OptGetVorgangspositionListFDokumentart
	// Dokumentnummer einer Drucksache oder eines Plenarprotokolls
	// Selektiert alle Entitäten, die mit der angegebenen Dokumentnummer verknüpft sind.
	// Kann wiederholt werden, um mehrere Dokumentnummern zu selektieren. Hinterlegt ist eine ODER-Suche.
	FDokumentnummer []string
	// ID einer verknüpften Drucksache
	// Selektiert alle Entitäten, die mit der angegebenen Drucksache verknüpft sind.
	FDrucksache OptInt
	// Typ der Drucksache
	// Selektiert alle Entitäten, die mit dem angegebenen Drucksachetyp verknüpft sind.
	FDrucksachetyp OptString
	// Fragenummer/Listenziffer
	// Selektiert alle Entitäten, die mit der angegebenen Fragenummer in einer Drucksache verknüpft
	// sind.
	// Kann wiederholt werden, um mehrere Fragenummern zu selektieren. Hinterlegt ist eine ODER-Suche.
	FFrageNummer []string
	// ID der Entität
	// Kann wiederholt werden, um mehrere Entitäten zu selektieren.
	FID []int
	// ID eines verknüpften Plenarprotokolls
	// Selektiert alle Entitäten, die mit dem angegebenen Plenarprotokoll verknüpft sind.
	FPlenarprotokoll OptInt
	// Ressort (federführend)
	// Selektiert alle Entitäten, die mit dem angegebenen federführenden Ressort in einer Drucksache
	// verknüpft sind.
	// Kann wiederholt werden, um die Schnittmenge mehrerer Ressorts zu selektieren. Hinterlegt ist eine
	// UND-Suche.
	// Eine ODER-Suche über mehrere federführende Ressorts ist mit einer einzigen Abfrage nicht
	// möglich. Die federführenden Ressorts müssen dazu einzeln abgefragt werden.
	FRessortFdf []string
	// Titel
	// Selektiert alle Entitäten, die den angegebenen Suchbegriff im Titel enthalten.
	// Kann wiederholt werden, um mehrere Titel zu selektieren. Hinterlegt ist eine ODER-Suche.
	// Eine Einzelwortsuche ist möglich. Mehrere Suchbegriffe hintereinander werden als Phrase gesucht.
	FTitel []string
	// Urheber
	// Selektiert alle Entitäten, die mit dem angegebenen Urheber in einer Drucksache verknüpft sind.
	// Kann wiederholt werden, um die Schnittmenge mehrerer Urheber zu selektieren. Hinterlegt ist eine
	// UND-Suche.
	// Eine ODER-Suche über mehrere Urheber ist mit einer einzigen Abfrage nicht möglich. Die Urheber
	// müssen dazu einzeln abgefragt werden.
	FUrheber []string
	// ID eines verknüpften Vorgangs
	// Selektiert alle Entitäten, die mit dem angegebenen Vorgang verknüpft sind.
	FVorgang OptInt
	// Vorgangstyp
	// Selektiert alle Entitäten, die dem angegebenen Vorgangstyp zugeordnet sind.
	// Kann wiederholt werden, um mehrere Vorgangstypen zu selektieren. Hinterlegt ist eine ODER-Suche.
	FVorgangstyp []string
	// Vorgangstyp-Notation
	// Selektiert alle Entitäten, die der angegebenen Vorgangstyp-Notation zugeordnet sind.
	// Kann wiederholt werden, um mehrere Vorgangstypen zu selektieren. Hinterlegt ist eine ODER-Suche.
	FVorgangstypNotation []int
	// Nummer der Wahlperiode
	// Selektiert alle Entitäten, die der angegebenen Wahlperiode zugeordnet sind.
	// Kann wiederholt werden, um mehrere Wahlperioden zu selektieren. Hinterlegt ist eine ODER-Suche.
	FWahlperiode []int
	// Zuordnung der Entität zum Bundestag, Bundesrat, Bundesversammlung oder Europakammer.
	FZuordnung OptZuordnung
	// Position des Cursors zur Anfrage weiterer Entitäten
	// Übersteigt die Anzahl der gefundenen Entitäten das jeweilige Limit, muss eine Folgeanfrage
	// gestellt werden, um weitere Entitäten zu laden.
	// Eine Folgeanfrage wird gebildet, indem alle Parameter der ursprünglichen Anfrage wiederholt
	// werden und zusätzlich der cursor Parameter der letzten Antwort eingesetzt wird.
	// Es können solange Folgeanfragen gestellt werden, bis sich der cursor nicht mehr ändert. Dies
	// signalisiert, dass alle Entitäten geladen wurden.
	Cursor OptString
	// Steuert das Datenformat der Antwort, möglich sind JSON (voreingestellt) oder XML.
	Format OptGetVorgangspositionListFormat
}
