[package]
name = "poller"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "poller"
path = "main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dip = { path = "../dip" }
